# Generated by Django 3.1.3 on 2020-11-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Under Review', max_length=50),
        ),
        migrations.AlterField(
            model_name='claims',
            name='debtor_phone',
            field=models.PositiveIntegerField(),
        ),
    ]
