# Generated by Django 3.1.3 on 2020-11-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_auto_20201111_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='debt_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='claims',
            name='debt_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
