# Generated by Django 3.1.3 on 2020-11-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_auto_20201112_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='debt_amount',
            field=models.PositiveIntegerField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('NGN', 'NGN'), ('RMB', 'RMB'), ('USD', 'USD'), ('YEN', 'YEN')], default=0),
        ),
        migrations.AlterField(
            model_name='claims',
            name='debt_paid',
            field=models.PositiveIntegerField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('NGN', 'NGN'), ('RMB', 'RMB'), ('USD', 'USD'), ('YEN', 'YEN')], default=0),
        ),
    ]
