# Generated by Django 3.1.3 on 2020-11-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_auto_20201112_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='debt_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='debt_paid',
            field=models.PositiveIntegerField(),
        ),
    ]
